version: '3.8'
# networks:
#   k6:
#   grafana:
#   influxdb:
services:
  api:
    image: obitanatp/repo
    ports:
      - "4444:5444"  
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_HOST : db
      POSTGRES_USER : host
      POSTGRES_PASSWORD : pass
      POSTGRES_DB : crud
    ports:
      - 5432:5432
  # db:
  #   image: mysql
  #   # command: --default-authentication-plugin=mysql_native_password
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: pass
  #     MYSQL_USER: host
  #     MYSQL_PASSWORD: pass
  #   ports: 
  #     - 3456:3306  

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080      
  k6:
    image: grafana/k6:latest 
    ports:
      - "6565:6565"
    volumes:
      - ./samples:/scripts  
    environment:
      - K6_OUT=influxdb=http://172.31.3.78:8086/k6

  influxdb:
    image: influxdb:1.8
    networks:
      - k6
      - grafana
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6

  grafana:
    image: grafana/grafana:latest
    networks:
      - grafana
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    volumes:
      - ./grafana:/etc/grafana/provisioning/