- hosts: server
  remote_user: ubuntu
  become: true
  tasks:
    - name: Login DockerHub
      win_shell: echo "{{DOCKER_PASSWORD}}" | docker login -u "{{DOCKER_USERNAME}}" --password-stdin
    - name: Copy file
      copy:
        src: docker-compose.yml
        dest: /home/ubuntu/
    - name: Restart docker-compose
      win_shell: |
          docker-compose stop
          docker-compose rm -f
          docker-compose pull
          docker-compose up -d