{
 "title": "Jenkins: Performance and Health Overview",
 "description": "Jobs queue speeds and rates, Executors availability, Nodes status, Jenkins and JVM resource usage, Jenkins Job Status, and lot more.",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Building duration count",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jenkins_job_building_duration_count"
    }
   ]
  },
  {
   "title": "Job queue duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jenkins_job_queuing_duration" }
   ]
  },
  {
   "title": "Jenkins health",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jenkins_health_check_score" }
   ]
  },
  {
   "title": "Total Jobs",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "default_jenkins_builds_success_build_count_total"
    }
   ]
  },
  {
   "title": "JVM free memory",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(vm_memory_total_max - vm_memory_total_used) / vm_memory_total_max * 100.0"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vm_memory_total_used" }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vm_cpu_load" }
   ]
  },
  {
   "title": "Sucessful Jobs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jenkins_runs_success_total" }
   ]
  },
  {
   "title": "Failed Jobs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jenkins_runs_failure_total" }
   ]
  },
  {
   "title": "Jenkins queue size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jenkins_queue_size_value" }
   ]
  },
  {
   "title": "Executor free",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jenkins_executor_free_value" }
   ]
  },
  {
   "title": "Executors health",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 4, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(sum(jenkins_job_building_duration)/sum(jenkins_job_building_duration_count))"
    }
   ]
  },
  {
   "title": "Job Duration",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "default_jenkins_builds_last_build_duration_milliseconds"
    }
   ]
  },
  {
   "title": "Executor In-use",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jenkins_executor_in_use_value" }
   ]
  }
 ]
}